name: dropbox_colors
description: "Dropbox Colors"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/og-image.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora/Sora-Bold.ttf
          weight: 700
